### ISSUE TITLE
Connect UtBot Online to Public cloud server

### ISSUE THREAD

**Issue by asolqa** [UnitTestBot/unittestbot.github.io#3]

**Comment by korifey** [comment]
> Depends on [open sourcing UTBot Online Backend](https://github.com/UnitTestBot/unittestbot.github.io/issues/8)

### Problem
Currently [UTBot Online](https://unittestbot.github.io/utbot/) uses http intranet address as backend.

### Expected
- UTBot Bot Online Backend is deployed to public cloud (public and internal docs must be updated how to do it) 
- HTTPS is used instead of HTTP
