### ISSUE TITLE
Setup GitHub Actions for site build / deploy

### ISSUE THREAD

**Issue by korifey** [UnitTestBot/unittestbot.github.io#5]
### Problem
Developer must manually setup WSL/Linux machine and download correct versions of npm, yarn, gatsby, then build site and deploy it.

### Expected
GitHub action that build and deploy site [on click](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) 
> Note: Secrets must be enabled to allow only privelledged users to deploy site.

**Comment by victoriafomina** [comment]
#### What means site is deployed
Site is uploaded on github.io.

#### Steps to deploy site
1. Developer pushes to repository.
2. github.io site updates within a few seconds.

Thus after these steps site is deployed.

#### About allowing only privelledged users to deploy site
Site automatically deploys on push. Only users with the corresponding access can push to repository. Thus seems there is no need in enabling secrets.
