### ISSUE TITLE
Update links on UTBot Website to target actual information.

### ISSUE THREAD

**Issue by korifey** [UnitTestBot/unittestbot.github.io#7]
### Problems

Currently deployed site contains incorrect links (to intranet) or placeholders.
- Static: ![image](https://user-images.githubusercontent.com/361139/151946936-a6d922be-4d43-4512-aeae-088201f73965.png)
- Dynamic: ![image](https://user-images.githubusercontent.com/361139/151947290-c57e4899-b0f2-46f5-8705-0a7a952d3a23.png)

> Note: Dynamic link must be populated during site building procedure. Please look at intranet CI building script to verify every placeholder is substituted.

**Comment by victoriafomina** [comment]
1. Should CodeHub link be removed or replaced with a link on other source?
2. Release/Nightly (cpp):
- Where "Get Server Installer" should link?
- Where "Get VSCode Plugin" should link?
3. UnitTestBot Java
Should I just remove the string with the year?
4. Nightly (Java):
Where "Get VSCode Plugin" should link?
5. UnitTestBot Site footer:
What information should be placed on footer?

**Comment by korifey** [comment]
1. Replace with link to 
2. Ask Vlad and make only one link to the latest release of UTBotCpp release
3. Yes
4. Just remove it for now (unitl UTBot Java is opensourced)
5. Date when this site was deployed.

**Comment by victoriafomina** [comment]
1. With the link on https://github.com/UnitTestBot, right?

**Comment by victoriafomina** [comment]
5. As for now site deployment is publication on github.io (happens automatically by push to the source branch) can I put there build date instead?
