### ISSUE TITLE
Search doesn't work on the website

### ISSUE THREAD

**Issue by pavponn** [UnitTestBot/unittestbot.github.io#73]
**Description**

Search on the website doesn't return any results for queries that definitely should return non-empty list of documentation articles. E.g., queries like: "utbot", "klee", "test", "code", "coverage".

**To Reproduce**

1. Open https://www.utbot.org/
2. In the search bar, write any word from the list: utbot, klee, test, code, coverage.
3. Press search button
4. No results are shown

**Expected behavior**

Some documentation articles are shown for all the words from the list.

**Actual behavior**

No documentation articles are shown.

**Visual proofs (screenshots, logs, images)**

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/34245435/187171514-3f37abdb-f67a-4a06-9255-e5c9d2790b38.png">

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/34245435/187171581-39ac84d7-805b-4e6d-9233-5dccd3fa770b.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/34245435/187171659-dd4e4e4f-69ad-4889-892c-ee93c8bbdf4b.png">

**Comment by tyuldashev** [comment]
Currently search partially works, but can find only top and second level titles.
