### ISSUE TITLE
Open source UTBot Online backend

### ISSUE THREAD

**Issue by korifey** [UnitTestBot/unittestbot.github.io#8]
### Problems

1. UTBot Online is now in intranet git repository, so we need to create public repository for it 
2. Deploymet of UTBot Online is not 1-click

### Expected

1. Public repo for UTBot Online Backend
2. Artifacts of project build should be docker image that can be easily deployed on any linux host + shell script for deployment

> Note: 
> - UTBot Online URL must be a parameter for UTBot site deployment action
> - Need to verify it works with local deployment (e.g. WSL)
> - Build of docker image for UTBot Online Backend must automatically download latest executable UTBot

**Comment by victoriafomina** [comment]
1. Should docker image be stored in docker hub or it's enough to store docker compose file in UTBot Online Backend repository?
2. Are we planning to distribute UTBot Online? If so then should we add UTBot Online frontend in a docker container?
