### ISSUE TITLE
Test generation fails for Java -  String Examples: nullable string buffer

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/unittestbot.github.io#82]
**Description**

Test generation fails for Java -  String Examples: nullable string buffer, is valid (short) UUID 

**To Reproduce**

1. Open _https://www.utbot.org/utbot_ page
2. Press _Try it online_ button
3. Select Java
4. Select  String Examples: nullable string buffer, is valid (short) UUID
5. Press _Generate and Run Tests_

**Expected behavior**

Tests are supposed to be generated successfully.

**Actual behavior**

TEST GENERATION: FAILED

**Visual proofs (screenshots, logs, images)**

```java
Status Code: TEST_GENERATION_FAILED

TEST GENERATION: FAILED
/var/utbot/processing/utbot-java-813249/StringExamples.java:13: error: cannot find symbol
    return isNotBlank(uuid) && uuid
           ^
  symbol:   method isNotBlank(String)
  location: class StringExamples
1 error

TEST RUN: ERROR OCCURRED
[object Object]: no details


```

**Comment by victoriafomina** [comment]
Closed due to being fixed frontend bug.
