### ISSUE TITLE
Mobile. GIF demos are cut from the left side

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/unittestbot.github.io#87]
**Description**

GIF demos are partly cut by sides - part of the code is invisible.

**To Reproduce**

1. iPhone, Safari 
2. Open _https://www.utbot.org/_
3. Scroll down to screen records in GIF format

**Expected behavior**

All code snippets should be visible.

**Actual behavior**

Code is cut of by sides about 4 symbols from the left and even more from the right.
Screen in the demos is square.

**Visual proofs (screenshots, logs, images)**

![20221007-151434(WeLinkPC)](https://user-images.githubusercontent.com/37301492/194551403-54951cff-01bb-4b33-affb-05aed9fa4c96.jpg)

**Comment by alexeyfridman** [comment]
GIF demos are scrolled well to the right edge but not to the left one, they're cut only from the left side.
