### ISSUE TITLE
"Run Tests" button must run user code in isolation to 

### ISSUE THREAD

**Issue by korifey** [UnitTestBot/unittestbot.github.io#9]
### Problem

Currently, "Run Tests" button runs test, generated for user code (so **it runs user code**) on the same docker where UTBot Online Backend is located. Since user code can be malicious (or hang forever) it can severely damage the system.

### Expected

User code is run in separate docker container with restricted privelledges (e.g. no system calls are allowed). Additionally consider usage of [gVisor](https://gvisor.dev/docs/) tool.

**Comment by victoriafomina** [comment]
Should every user have its own docker container for running tests or we should have one common docker container for it?

**Comment by victoriafomina** [comment]
I found the measurement showing how much it takes to run docker container for different processors and configurations: https://github.com/moby/moby/issues/38077.

We can also try to measure it for our process: https://medium.com/@sujit.kumar731/measure-execution-time-of-docker-container-4fb64c3ce4cd.

First steps to let run every users' tests in separate container should be:

1. Find where starts the CLI process in backend (ProcessBuilder must do it).
2. Create Dockerfile which can run CLI.
3. Replace the code running CLI process with the code running Dockerfile.
