### ISSUE TITLE
Site header. Java/Kotlin stays highlighted no matter what has been chosen

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/unittestbot.github.io#98]
**Description**

Site header. Java/Kotlin stays highlighted no matter what has been chosen.

**To Reproduce**

1. Open _https://www.utbot.org
2. Check header. Java/Kotlin is displayed bold.
3. Click on other header item: for example Python.

**Expected behavior**

Java/Kotlin should become regular.

**Actual behavior**

Java/Kotlin stays highlighted no matter which item is chosen.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/37301492/194906321-1bfd7341-89f0-41fb-b0f3-eca617021f39.png)

![image](https://user-images.githubusercontent.com/37301492/194906340-93667886-538d-4df0-ae1d-d7b03cd71e47.png)

**Comment by tyuldashev** [comment]
Additional note: when open CPP docs I would expect that proper item highlighted. Currently 'Java/Kotlin' always highlighted.

![image](https://user-images.githubusercontent.com/10035839/195069118-cd6d8cbd-4726-4478-a454-b745e1938baf.png)
